### ISSUE TITLE
DeleteDeadParticles

### ISSUE THREAD

**Issue by rbooth200** [gandalfcode/gandalf#103]
There are currently some things about DeleteDeadParticles that are unsatisfactory:
 
- We have two identical copies of the function
- It invalidates the ghosts and we do not currently have a way to check that the ghosts are valid before using them.

The second problem could be solved pragmatically by just 'flagging' that the ghosts are invalid and checking this flag before walks are done. Alternatively it could be made valid. See the discussion [here](https://github.com/gandalfcode/gandalf/pull/102)

**Comment by giovanni-rosotti** [comment]
The first problem is fixed in #128 . Do we have plans to fix the second one soon, or should we move the issue to a future milestone?

**Comment by rbooth200** [comment]
I will have a think about the second one. There would still be a lot of places in which we need to check the tree's validity. The easiest solution would be to check the flags each (ghost) tree walk. It should be cheap, but its a lot of checks...

**Comment by rbooth200** [comment]
Can we close this issue? DeleteDeadParticles invalidates the whole tree, not just the ghost particles so there is probably not much point in flagging anything.

**Comment by rbooth200** [comment]
Bump

**Comment by giovanni-rosotti** [comment]
I agree it's fine to close this - closing
