### ISSUE TITLE
Jeans test

### ISSUE THREAD

**Issue by rbooth200** [gandalfcode/gandalf#112]
The jeans test currently highlights the inaccuracy of tyradiational tree based methods when the gravitational forces nearly cancel. We need to implement a relative opening criterion that will work robustly for problems of this nature, a la GADGET2.

**Comment by rbooth200** [comment]
At the moment there seems to be a serious problem with periodic gravity in the master branch. Even when all of the nodes are opened the result seems to be junk...

**Comment by giovanni-rosotti** [comment]
Done in #118
