### ISSUE TITLE
Compile complete test suite

### ISSUE THREAD

**Issue by dhubber** [gandalfcode/gandalf#17]
Complete python scripts that allow us to perform a complete test suite of the code.  Will be useful for our own validation and debugging of the code, plus useful for other people being able to quickly run the code to show its capabilities.

**Comment by dhubber** [comment]
We really still need to do this I think!  I guess it's been partly done for the Travis building, but should also be done for the users.  Maybe what would be better is to have a script to run all the paper tests since that will run the simulations and generate the paper figures for anyone wanting to see it in action on their own machine.

**Comment by giovanni-rosotti** [comment]
This is now done in #109 . The Jeans test is missing but there is already a separate issue for that. Closing the issue
