### ISSUE TITLE
Add additional file formats

### ISSUE THREAD

**Issue by dhubber** [gandalfcode/gandalf#30]
Add additional file formats to gandalf, in particular dragon and hdf5 formats

**Comment by giovanni-rosotti** [comment]
The hdf5 format needs some discussion. hdf5 is only a container, not a format (think to it like a filesystem with folders and files) - we need to decide how we want to structure the data inside.
A simple possibility could be a folder (group in hdf5 terminology) for each particle type, and inside each group a file for each array (or can you dump directly structs?). Header information can go in the root folder presumably

**Comment by giovanni-rosotti** [comment]
There is already a separate issue for HDF5, so I'm closing this. I don't think dragon is important enough to justify the time needed, unless a user really needs it
