### ISSUE TITLE
Improved code setup

### ISSUE THREAD

**Issue by dhubber** [gandalfcode/gandalf#33]
Suggested at the school that we have either for example a proper setup.py, or some kind of 'make install', or something similar to : 
move executable files,
move or link python files,
set-up environment variables, etc..

**Comment by giovanni-rosotti** [comment]
See pull request #43

**Comment by giovanni-rosotti** [comment]
Shouldn't we close this given that the fix has been merged? Or is there anything else that should be done?

**Comment by rbooth200** [comment]
I will close it - what we have is certainly good enough for now.
