### ISSUE TITLE
Analytical solutions

### ISSUE THREAD

**Issue by rbooth200** [gandalfcode/gandalf#42]
The userguide mentions that some additional analytical solutions would be nice. I already have a python script that solves the sedov problem, which might be useful. I've attached it here in case.
[SedovSolution.py.txt](https://github.com/gandalfcode/gandalf/files/31041/SedovSolution.py.txt)

**Comment by dhubber** [comment]
The Sedov solution has already been integrated into the Python script and works perfectly fine.  Any additional analytical solutions can be added as needed into the same file in the future.
