### ISSUE TITLE
All z-component vector quantities (e.g. z, vz, az) are zero with python viewer

### ISSUE THREAD

**Issue by dhubber** [gandalfcode/gandalf#51]
When loading a simulation and printing either z, a z-component (e.g. vz, az) or a component that relies that z (e.g. r, vr), it appears that z is always zero and therefore everything's incorrect.  I tried an earlier version, before some recent changes to the snapshot class, and it worked fine, so I'm guessing there was a bug introduced in the recent changes.  It obviously only affects 3d simulations.

**Comment by giovanni-rosotti** [comment]
See #52. You are right, I introduced a bug without realising... an 'else' that shouldn't have been there

**Comment by dhubber** [comment]
Yes, looks fine now.
