### ISSUE TITLE
Circular Dependency in Analysis 

### ISSUE THREAD

**Issue by ajw278** [gandalfcode/gandalf#65]
Small issue in the analysis Python code (mine is an old version but appears to still be there):

data_fetcher.py ---imports-->  facade (SimBuffer)  --imports--> commandsource --imports--> data_fetcher (UserQuantity)

I solved by moving the SimBuffer import (in data_fetcher.py) and data_fetcher import (in commandsource.py) to the bottom of the respective files.

**Comment by giovanni-rosotti** [comment]
Sorry Andrew - had missed this completely. I think if you first import facade and then data_fetcher everything should be fine, can you please confirm?

**Comment by giovanni-rosotti** [comment]
This seems to have solved the problem - closing the issue
