### ISSUE TITLE
kernfac

### ISSUE THREAD

**Issue by rbooth200** [gandalfcode/gandalf#88]
What is kernfac? It is always set to 1.0 so why do we have it?  I'm inclined to get rid of it since it is one of many ways in which we destroy encapsulation.

**Comment by dhubber** [comment]
It is a relic from the deleted Godunov Sph implementation.  Basically it
had some weird kernel convolution that meant you needed to search for
root-2 times the normal kernel extent.  So kernfac was 1 for Sph and root-2
for Godunov Sph.  Short story is, yes, it can be purged from existence now
:-)

**Comment by rbooth200** [comment]
Done.
