### ISSUE TITLE
Kelvin-Helmholtz fails with Meshless test

### ISSUE THREAD

**Issue by dhubber** [gandalfcode/gandalf#93]
The Kelvin-helmholtz test using the khi.dat file in tests/hydro_tests changing the sim parameter to mfvmuscl fails on the master branch (and other merged/rebased branches) with the assertion : 

Assertion failed: (itype != none), function CopyDataToGhosts, file /Users/dah/code/gandalf/src/MeshlessFV/MfvCommon.cpp, line 361

Doesn't seem to happen with other ICs so not sure yet if it's a problem with setting up the ICs or something with periodic ghosts in the meshless (or a combination of the two).  Used g++ 5.4 with OpenMP (2 cores) but no MPI.

**Comment by rbooth200** [comment]
I'm aware of this issue. It was introduced by the reallocate branch. The call to 
`mfvneib->SearchBoundaryGhostParticles(tghost, simbox, mfv)`
on[line 105 of MeshlessFV/MfvMusclSimulation.cpp](https://github.com/gandalfcode/gandalf/blob/master/src/MeshlessFV/MfvMusclSimulation.cpp#L105) invalidates the partdata pointer. I've fixed the bug the [timing branch](https://github.com/gandalfcode/gandalf/blob/timing/src/MeshlessFV/MfvMusclSimulation.cpp#L106), but really we should stop creating local pointers to the particle data structure and let functions create their own from the hydro object when needed.

**Comment by dhubber** [comment]
Ah, ok.  Didn't come across it myself before and didn't notice it being flagged up (trying to get my own branch working before diving into the others).  Anyway, in that case I'll close this issue and also submit a pull request for my branch so (unique) issues with it can be discussed there.
