### ISSUE TITLE
Restock pruned tree

### ISSUE THREAD

**Issue by rbooth200** [gandalfcode/gandalf#95]
At the moment it appears that we are not restocking the pruned trees. This surely means they are out of date resulting in the wrong force update.

The best solution is likely to be to export the leaf cells of the pruned trees after restocking and rebuild them locally.

**Comment by giovanni-rosotti** [comment]
Related to this issue (but less serious), we are also not updating the hs in the tree after h has been recomputed. See discussion in #92 for how to proceed

**Comment by giovanni-rosotti** [comment]
See #100 . The update of h is no longer a concern because we are restocking the pruned trees after the h calculation - so they will have the right one.

**Comment by giovanni-rosotti** [comment]
Fixed in #115
